# dbt run-operation generate_source --args '{"schema_name": "movies_data_pradeep", "generate_columns": true, "include_data_types": false}'
version: 2

sources:
  - name: movies_data_pradeep
    tables:
      - name: movies_raw
        identifier: movies_raw
        columns:
          - name: adult
          - name: belongs_to_collection
          - name: budget
          - name: genres
          - name: homepage
          - name: id
          - name: imdb_id
          - name: original_language
          - name: original_title
          - name: overview
          - name: popularity
          - name: poster_path
          - name: production_companies
          - name: production_countries
          - name: release_date
          - name: revenue
          - name: runtime
          - name: spoken_languages
          - name: status
          - name: tagline
          - name: title
          - name: video
          - name: vote_average
          - name: vote_count
          - name: load_date

      - name: ratings_raw
        columns:
          - name: userid
          - name: movieid
          - name: rating
          - name: timestamp
          - name: load_date