name: Deploy Cloud Function

on: [push]

jobs:
  test:
    name: Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy Cloud Function
        run: |
          gcloud functions deploy load_csv_to_bigquery \
            --runtime python310 \
            --trigger-resource se-data-landing-pradeep \
            --trigger-event google.storage.object.finalize \
            --entry-point load_csv_to_bigquery \
            --set-env-vars DATASET_ID=ee-india-se-data.movies_data_pradeep,TABLE_ID=movies_raw \
            --source .
