# name: Deploy Cloud Function

# on:
#   push:
#     branches:
#       - main

# jobs:
#   deploy:
#     runs-on: self-hosted
#     steps:
#       - name: Checkout code
#         uses: actions/checkout@v2

#       - name: Set up Cloud SDK
#         uses: google-github-actions/setup-gcloud@v1
#         with:
#           project_id: ${{ secrets.GCP_PROJECT_ID }}
#           service_account_key: ${{ secrets.GCP_SA_KEY }}
#           export_default_credentials: true

#       - name: Deploy Cloud Function
#         run: |
#           gcloud functions deploy load_csv_to_bigquery \
#             --runtime python310 \
#             --trigger-resource se-data-landing-pradeep \
#             --trigger-event google.storage.object.finalize \
#             --entry-point load_csv_to_bigquery \
#             --set-env-vars DATASET_ID=ee-india-se-data.movies_data_pradeep,TABLE_ID=movies_raw \
#             --source .
name: Deploy Cloud Function

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest  

    steps:
      - uses: actions/checkout@v2

      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          project_id: ${{ secrets.GCP_PROJECT_ID }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      - name: Install dependencies (if applicable)
        run: |
          cd cloudfunction  
          python -m pip install -r requirements.txt  # Example for Python, adjust for your language

      - name: Deploy Cloud Function
        run: |
          gcloud functions deploy your_function_name \
            --runtime your_function_runtime \  # Replace with your function's runtime (e.g., python310)
            --trigger-resource your_trigger_resource \  # Replace with your trigger resource name
            --trigger-event your_trigger_event \  # Replace with your trigger event (e.g., google.storage.object.finalize)
            --entry-point your_function_entry_point \  # Replace with your function's entry point
            --set-env-vars DATASET_ID=your_dataset_id,TABLE_ID=your_table_id  # Replace with your environment variables
            --source .
